### ISSUE TITLE
Incompatibility with some LifeCycleEvents

### ISSUE THREAD

**Issue by ruimarinho** [simplethings/SimpleThingsFormSerializerBundle#18]
When using Backbone.js, a common practice is to return a new `model` representation after it is processed by the update action (usually a `PUT` request). This is useful to update the client-side model with server-side generated data like `updatedAt` fields or other domain logic data.

However, Backbone.js does not work well with differential updates when saving models (`PATCH` support is funky) - it always sends the complete model object back to the server. Because of the way this is handled, any update action needs to return a complete form serialized back to the client after a successful save - and this means I need the `updatedAt` field on that form.

The problem is that the [unserializeForm](https://github.com/simplethings/SimpleThingsFormSerializerBundle/blob/master/Form/EventListener/BindRequestListener.php#L111) will now let the Form component set that value on the object, as if it was manually set. This breaks LifeCycleEvents that depend on this check to determine wether a new value should be set or not (see the [TimestampableListener](https://github.com/l3pp4rd/DoctrineExtensions/blob/master/lib/Gedmo/Timestampable/TimestampableListener.php#L69) from Gedmo).

Any ideas or workarounds to solve this?

**Comment by stof** [comment]
@ruimarinho set the field as disabled, and the Form component will not modify its value

**Comment by ruimarinho** [comment]
@stof thanks, this solves the issue - the listener now updates the `updatedAt` property correctly. However, the entity serialized is not up to date (`$this->renderForm($this->form)` returns the previous `updatedAt` value). I tried refreshing the entity but it didn't work. Any idea why the serializer is not picking up the new value?

**Comment by beberlei** [comment]
The issue is that the form is bound only once, and every change to the object is not actually synchronized back to the form instance.

**Comment by ruimarinho** [comment]
Exactly. The workaround is to bind a new form instance in case of success? What do you suggest?
