### ISSUE TITLE
renderFormView HTTP error code

### ISSUE THREAD

**Issue by ruimarinho** [simplethings/SimpleThingsFormSerializerBundle#20]
The documentation mentions that the `renderFormView` returns a `412 Precondition Failed` error if the form validation fails. The only thing that is similar to that method is `renderForm` and it doesn't seem to set any status code.
1. Can you tell me where exactly is this being handled?
2. In your opinion, wouldn't `422 Unprocessable Entity` be more appropriate? See [Section 11.2](http://tools.ietf.org/html/rfc4918#section-11.2) for a more descriptive argument.

_Addendum_: in terms of Backbone.js, any 4xx error will trigger the error handlers, so it's really more of a conceptual point.

**Comment by beberlei** [comment]
1. this is not implemented yet
2. 422 is not an HTTP error, its a WebDav error.

**Comment by ruimarinho** [comment]
@beberlei it's still a valid HTTP status code in any case - see the [IANA registry](http://www.iana.org/assignments/http-status-codes/http-status-codes.xml). 

Also, Github API uses `422 Unprocessable Entity` too - see their [API documentation](http://developer.github.com/v3/).
